### ISSUE TITLE
Project with w5500 and bme280

### ISSUE THREAD

**Issue by SrRockabilly** [maxgerhardt/pio-bluepill-w5500-ethernet-mqtt-client#1]
Hi there, 
your project gives me the boost to start mine. I have a problem related here: https://www.stm32duino.com/viewtopic.php?f=10&t=1163
If you dont mind to take a look, it would be nice to have your opinion.

**Comment by maxgerhardt** [comment]
Closing since you've discovered it's a hardware issue per https://www.stm32duino.com/viewtopic.php?p=7970#p7970.
